/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresetIndexRouteImport } from './routes/preset/index'
import { Route as PersonaIndexRouteImport } from './routes/persona/index'
import { Route as LorebookIndexRouteImport } from './routes/lorebook/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as CharacterIndexRouteImport } from './routes/character/index'
import { Route as PresetNewRouteImport } from './routes/preset/new'
import { Route as PersonaNewRouteImport } from './routes/persona/new'
import { Route as LorebookNewRouteImport } from './routes/lorebook/new'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as CharacterNewRouteImport } from './routes/character/new'
import { Route as PresetPresetIdIndexRouteImport } from './routes/preset/$presetId/index'
import { Route as PersonaPersonaIdIndexRouteImport } from './routes/persona/$personaId/index'
import { Route as LorebookLorebookIdIndexRouteImport } from './routes/lorebook/$lorebookId/index'
import { Route as ConversationChatIdIndexRouteImport } from './routes/conversation/$chatId/index'
import { Route as ChatChatIdIndexRouteImport } from './routes/chat/$chatId/index'
import { Route as CharacterCharacterIdIndexRouteImport } from './routes/character/$characterId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetIndexRoute = PresetIndexRouteImport.update({
  id: '/preset/',
  path: '/preset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIndexRoute = PersonaIndexRouteImport.update({
  id: '/persona/',
  path: '/persona/',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebookIndexRoute = LorebookIndexRouteImport.update({
  id: '/lorebook/',
  path: '/lorebook/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIndexRoute = CharacterIndexRouteImport.update({
  id: '/character/',
  path: '/character/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetNewRoute = PresetNewRouteImport.update({
  id: '/preset/new',
  path: '/preset/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaNewRoute = PersonaNewRouteImport.update({
  id: '/persona/new',
  path: '/persona/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebookNewRoute = LorebookNewRouteImport.update({
  id: '/lorebook/new',
  path: '/lorebook/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterNewRoute = CharacterNewRouteImport.update({
  id: '/character/new',
  path: '/character/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetPresetIdIndexRoute = PresetPresetIdIndexRouteImport.update({
  id: '/preset/$presetId/',
  path: '/preset/$presetId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaPersonaIdIndexRoute = PersonaPersonaIdIndexRouteImport.update({
  id: '/persona/$personaId/',
  path: '/persona/$personaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LorebookLorebookIdIndexRoute = LorebookLorebookIdIndexRouteImport.update({
  id: '/lorebook/$lorebookId/',
  path: '/lorebook/$lorebookId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationChatIdIndexRoute = ConversationChatIdIndexRouteImport.update({
  id: '/conversation/$chatId/',
  path: '/conversation/$chatId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdIndexRoute = ChatChatIdIndexRouteImport.update({
  id: '/chat/$chatId/',
  path: '/chat/$chatId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCharacterIdIndexRoute =
  CharacterCharacterIdIndexRouteImport.update({
    id: '/character/$characterId/',
    path: '/character/$characterId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character/new': typeof CharacterNewRoute
  '/chat/new': typeof ChatNewRoute
  '/lorebook/new': typeof LorebookNewRoute
  '/persona/new': typeof PersonaNewRoute
  '/preset/new': typeof PresetNewRoute
  '/character': typeof CharacterIndexRoute
  '/chat': typeof ChatIndexRoute
  '/lorebook': typeof LorebookIndexRoute
  '/persona': typeof PersonaIndexRoute
  '/preset': typeof PresetIndexRoute
  '/character/$characterId': typeof CharacterCharacterIdIndexRoute
  '/chat/$chatId': typeof ChatChatIdIndexRoute
  '/conversation/$chatId': typeof ConversationChatIdIndexRoute
  '/lorebook/$lorebookId': typeof LorebookLorebookIdIndexRoute
  '/persona/$personaId': typeof PersonaPersonaIdIndexRoute
  '/preset/$presetId': typeof PresetPresetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character/new': typeof CharacterNewRoute
  '/chat/new': typeof ChatNewRoute
  '/lorebook/new': typeof LorebookNewRoute
  '/persona/new': typeof PersonaNewRoute
  '/preset/new': typeof PresetNewRoute
  '/character': typeof CharacterIndexRoute
  '/chat': typeof ChatIndexRoute
  '/lorebook': typeof LorebookIndexRoute
  '/persona': typeof PersonaIndexRoute
  '/preset': typeof PresetIndexRoute
  '/character/$characterId': typeof CharacterCharacterIdIndexRoute
  '/chat/$chatId': typeof ChatChatIdIndexRoute
  '/conversation/$chatId': typeof ConversationChatIdIndexRoute
  '/lorebook/$lorebookId': typeof LorebookLorebookIdIndexRoute
  '/persona/$personaId': typeof PersonaPersonaIdIndexRoute
  '/preset/$presetId': typeof PresetPresetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character/new': typeof CharacterNewRoute
  '/chat/new': typeof ChatNewRoute
  '/lorebook/new': typeof LorebookNewRoute
  '/persona/new': typeof PersonaNewRoute
  '/preset/new': typeof PresetNewRoute
  '/character/': typeof CharacterIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/lorebook/': typeof LorebookIndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/preset/': typeof PresetIndexRoute
  '/character/$characterId/': typeof CharacterCharacterIdIndexRoute
  '/chat/$chatId/': typeof ChatChatIdIndexRoute
  '/conversation/$chatId/': typeof ConversationChatIdIndexRoute
  '/lorebook/$lorebookId/': typeof LorebookLorebookIdIndexRoute
  '/persona/$personaId/': typeof PersonaPersonaIdIndexRoute
  '/preset/$presetId/': typeof PresetPresetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character/new'
    | '/chat/new'
    | '/lorebook/new'
    | '/persona/new'
    | '/preset/new'
    | '/character'
    | '/chat'
    | '/lorebook'
    | '/persona'
    | '/preset'
    | '/character/$characterId'
    | '/chat/$chatId'
    | '/conversation/$chatId'
    | '/lorebook/$lorebookId'
    | '/persona/$personaId'
    | '/preset/$presetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character/new'
    | '/chat/new'
    | '/lorebook/new'
    | '/persona/new'
    | '/preset/new'
    | '/character'
    | '/chat'
    | '/lorebook'
    | '/persona'
    | '/preset'
    | '/character/$characterId'
    | '/chat/$chatId'
    | '/conversation/$chatId'
    | '/lorebook/$lorebookId'
    | '/persona/$personaId'
    | '/preset/$presetId'
  id:
    | '__root__'
    | '/'
    | '/character/new'
    | '/chat/new'
    | '/lorebook/new'
    | '/persona/new'
    | '/preset/new'
    | '/character/'
    | '/chat/'
    | '/lorebook/'
    | '/persona/'
    | '/preset/'
    | '/character/$characterId/'
    | '/chat/$chatId/'
    | '/conversation/$chatId/'
    | '/lorebook/$lorebookId/'
    | '/persona/$personaId/'
    | '/preset/$presetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterNewRoute: typeof CharacterNewRoute
  ChatNewRoute: typeof ChatNewRoute
  LorebookNewRoute: typeof LorebookNewRoute
  PersonaNewRoute: typeof PersonaNewRoute
  PresetNewRoute: typeof PresetNewRoute
  CharacterIndexRoute: typeof CharacterIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  LorebookIndexRoute: typeof LorebookIndexRoute
  PersonaIndexRoute: typeof PersonaIndexRoute
  PresetIndexRoute: typeof PresetIndexRoute
  CharacterCharacterIdIndexRoute: typeof CharacterCharacterIdIndexRoute
  ChatChatIdIndexRoute: typeof ChatChatIdIndexRoute
  ConversationChatIdIndexRoute: typeof ConversationChatIdIndexRoute
  LorebookLorebookIdIndexRoute: typeof LorebookLorebookIdIndexRoute
  PersonaPersonaIdIndexRoute: typeof PersonaPersonaIdIndexRoute
  PresetPresetIdIndexRoute: typeof PresetPresetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preset/': {
      id: '/preset/'
      path: '/preset'
      fullPath: '/preset'
      preLoaderRoute: typeof PresetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/': {
      id: '/persona/'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebook/': {
      id: '/lorebook/'
      path: '/lorebook'
      fullPath: '/lorebook'
      preLoaderRoute: typeof LorebookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/': {
      id: '/character/'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preset/new': {
      id: '/preset/new'
      path: '/preset/new'
      fullPath: '/preset/new'
      preLoaderRoute: typeof PresetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/new': {
      id: '/persona/new'
      path: '/persona/new'
      fullPath: '/persona/new'
      preLoaderRoute: typeof PersonaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebook/new': {
      id: '/lorebook/new'
      path: '/lorebook/new'
      fullPath: '/lorebook/new'
      preLoaderRoute: typeof LorebookNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/new': {
      id: '/character/new'
      path: '/character/new'
      fullPath: '/character/new'
      preLoaderRoute: typeof CharacterNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preset/$presetId/': {
      id: '/preset/$presetId/'
      path: '/preset/$presetId'
      fullPath: '/preset/$presetId'
      preLoaderRoute: typeof PresetPresetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$personaId/': {
      id: '/persona/$personaId/'
      path: '/persona/$personaId'
      fullPath: '/persona/$personaId'
      preLoaderRoute: typeof PersonaPersonaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorebook/$lorebookId/': {
      id: '/lorebook/$lorebookId/'
      path: '/lorebook/$lorebookId'
      fullPath: '/lorebook/$lorebookId'
      preLoaderRoute: typeof LorebookLorebookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$chatId/': {
      id: '/conversation/$chatId/'
      path: '/conversation/$chatId'
      fullPath: '/conversation/$chatId'
      preLoaderRoute: typeof ConversationChatIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId/': {
      id: '/chat/$chatId/'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$characterId/': {
      id: '/character/$characterId/'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof CharacterCharacterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterNewRoute: CharacterNewRoute,
  ChatNewRoute: ChatNewRoute,
  LorebookNewRoute: LorebookNewRoute,
  PersonaNewRoute: PersonaNewRoute,
  PresetNewRoute: PresetNewRoute,
  CharacterIndexRoute: CharacterIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  LorebookIndexRoute: LorebookIndexRoute,
  PersonaIndexRoute: PersonaIndexRoute,
  PresetIndexRoute: PresetIndexRoute,
  CharacterCharacterIdIndexRoute: CharacterCharacterIdIndexRoute,
  ChatChatIdIndexRoute: ChatChatIdIndexRoute,
  ConversationChatIdIndexRoute: ConversationChatIdIndexRoute,
  LorebookLorebookIdIndexRoute: LorebookLorebookIdIndexRoute,
  PersonaPersonaIdIndexRoute: PersonaPersonaIdIndexRoute,
  PresetPresetIdIndexRoute: PresetPresetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
